import { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: [
          '/admin/',
          '/api/',
          '/dashboard/',
          '/login',
          '/register',
          '/create-listing',
          '/checkout/',
          '/cart/',
          '/account/',
          '/orders/',
          '/listings/',
        ],
      },
      {
        userAgent: 'Googlebot',
        allow: '/',
        disallow: [
          '/admin/',
          '/api/',
          '/dashboard/',
          '/login',
          '/register',
          '/create-listing',
        ],
        crawlDelay: 0,
      },
      // AI crawlers - explicitly allowed for AI search visibility
      // (ChatGPT, Claude, Perplexity, Gemini). Same private-area
      // restrictions as everyone else.
      {
        userAgent: 'GPTBot',
        allow: '/',
        disallow: [
          '/admin/',
          '/api/',
          '/dashboard/',
          '/login',
          '/register',
          '/create-listing',
          '/checkout/',
          '/cart/',
          '/account/',
          '/orders/',
          '/listings/',
        ],
      },
      {
        userAgent: 'OAI-SearchBot',
        allow: '/',
        disallow: [
          '/admin/',
          '/api/',
          '/dashboard/',
          '/login',
          '/register',
          '/create-listing',
          '/checkout/',
          '/cart/',
          '/account/',
          '/orders/',
          '/listings/',
        ],
      },
      {
        userAgent: 'ClaudeBot',
        allow: '/',
        disallow: [
          '/admin/',
          '/api/',
          '/dashboard/',
          '/login',
          '/register',
          '/create-listing',
          '/checkout/',
          '/cart/',
          '/account/',
          '/orders/',
          '/listings/',
        ],
      },
      {
        userAgent: 'PerplexityBot',
        allow: '/',
        disallow: [
          '/admin/',
          '/api/',
          '/dashboard/',
          '/login',
          '/register',
          '/create-listing',
          '/checkout/',
          '/cart/',
          '/account/',
          '/orders/',
          '/listings/',
        ],
      },
      {
        userAgent: 'Google-Extended',
        allow: '/',
        disallow: [
          '/admin/',
          '/api/',
          '/dashboard/',
          '/login',
          '/register',
          '/create-listing',
          '/checkout/',
          '/cart/',
          '/account/',
          '/orders/',
          '/listings/',
        ],
      },
    ],
    sitemap: 'https://www.sellbookmedia.com/sitemap.xml',
  }
}